common_labels:
   project: "test"
   environment: "dev"

compute:
  machine_type: "e2-medium"
  zones: "us-central1-a"
  image: "debian-cloud/debian-11"
  disk_size_gb: 12
  subnetname: default
  networktag: public 
  project_name: gcplearning24
