common_labels:
   project: "test"
   environment: "dev"

project_name: gcplearning24
compute:
  machine_type: "e2-medium"
  zones: "us-central1-a"
  image: "debian-cloud/debian-11"
  disk_size_gb: 12
  subnetname: default
  networktag: public 
vpn:
  machine_type: "e2-medium"
  image: "ubuntu-os-cloud/ubuntu-2004-lts"
  disk_size_gb: 12
  zone: "us-central1-b"

db:
  db_instance_name: "test"
  database_version: "POSTGRES_16"

  
  