resource "google_compute_global_address" "private_ip_address" {
    project = var.project_name
    name          = "global-psconnect-ip"
    purpose       = "VPC_PEERING"
    address_type = "INTERNAL"
    prefix_length = 16
    network =  var.vpc_id
}

resource "google_service_networking_connection" "private_vpc_connection" {
    network = var.vpc_id
    service       = "servicenetworking.googleapis.com"
    reserved_peering_ranges = [google_compute_global_address.private_ip_address.name]
}

resource "random_id" "db_name_suffix" {
  byte_length = 4
}

resource "google_sql_database_instance" "db_instance" {
  depends_on       = [google_service_networking_connection.private_vpc_connection]
  name                  = "${var.project_name}-${terraform.workspace}-${var.db_instance_name}-${random_id.db_name_suffix.hex}"
  region           = var.region
  database_version = var.database_version
  deletion_protection  = var.deletion_protection

  settings {
    tier            = "db-custom-4-15360"
    disk_autoresize = var.disk_autoresize
    availability_type = var.availability_type

    ip_configuration {
      ipv4_enabled    = "false"
      private_network = "projects/${var.project_name}/global/networks/${var.network_name}"   
    }
    user_labels = {
    environment = "${terraform.workspace}"
    project = "${var.project_name}"
    name = "${var.project_name}-${terraform.workspace}-${var.db_instance_name}"
    managedby = "terraform"

  }
  }
}

resource "google_sql_database" "db" {
  name       = var.db_name
  instance   = google_sql_database_instance.db_instance.name
  depends_on = [google_sql_user.user]
}

resource "random_string" "autogenerated_db_password" {
  length  = 16
  special = false
}

resource "google_sql_user" "user" {
  name     = "admin"
  instance = google_sql_database_instance.db_instance.name

  password = var.db_password != "" ? var.db_password : random_string.autogenerated_db_password.result
}



